const { GoogleGenerativeAI } = require("@google/generative-ai");
const fs = require("fs");
const TestSeries = require("../models/testSeries");
const Question = require("../models/question");
const { uploadToCloudinary } = require("../config/cloudinary");
const AppError = require("../utils/AppError");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

exports.autoIngest = async (req, res, next) => {
  try {
    if (!req.file) {
      return next(new AppError("Please upload a PDF file", 400));
    }

    const { title, category, seriesId } = req.body;
    if (!title) return next(new AppError("Title is required", 400));

    // 1. Upload PDF to Cloudinary for storage/download
    const cloudinaryResult = await uploadToCloudinary(req.file.path, "quizaro_pdfs");
    const pdfUrl = cloudinaryResult;

    // 2. Extract Text from PDF
    const dataBuffer = fs.readFileSync(req.file.path);
    const pdf = require("pdf-parse");
    const pdfData = await pdf(dataBuffer);
    const extractedText = pdfData.text;

    if (!extractedText || extractedText.trim().length < 50) {
      return next(new AppError("PDF contains insufficient text for MCQ generation", 400));
    }

    // 3. Generate MCQs using Gemini
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    
    const prompt = `
      Extract multiple choice questions from the following text. 
      For each question, provide exactly 4 options. 
      DO NOT provide the correct answer. 
      Return the result as a JSON array of objects with this structure:
      [{ "questionText": "...", "options": [{ "text": "..." }, { "text": "..." }, { "text": "..." }, { "text": "..." }] }]
      
      IMPORTANT: Return ONLY the JSON array. Do not include any explanation or markdown blocks.
      
      Text: ${extractedText.substring(0, 10000)}
    `;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    let mcqs = [];
    
    try {
      const text = response.text();
      console.log("Gemini Raw Response:", text);
      
      // Improved JSON extraction regex
      const jsonMatch = text.match(/\[\s*\{.*\}\s*\]/s);
      const cleanText = jsonMatch ? jsonMatch[0] : text.replace(/```json|```/g, "").trim();
      
      mcqs = JSON.parse(cleanText);
    } catch (err) {
      console.error("Gemini JSON Parse Error:", err);
      return next(new AppError("Neural pattern parsing failed. The AI generated an invalid data structure. Please try a cleaner PDF.", 500));
    }

    // 4. Create Test and Questions
    const test = await TestSeries.create({
      title,
      category: category || "General",
      seriesId: seriesId || null,
      pdfUrl,
      isAutoGenerated: true,
      createdBy: req.user.id,
      isPublished: true, // Auto-publish as requested
      totalQuestions: mcqs.length
    });

    const questionsData = mcqs.map((q, index) => ({
      testId: test._id,
      questionText: q.questionText,
      options: q.options,
      correctOption: 0, // Default to 0 since no answer is provided
      orderIndex: index
    }));

    await Question.insertMany(questionsData);

    // Clean up local file
    fs.unlinkSync(req.file.path);

    res.status(201).json({
      message: "Intelligence successfully ingested and MCQs generated.",
      testId: test._id,
      pdfUrl,
      questionCount: mcqs.length
    });

  } catch (err) {
    if (req.file && fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);
    next(err);
  }
};
