const { GoogleGenerativeAI } = require("@google/generative-ai");
const fs = require("fs");
const TestSeries = require("../models/testSeries");
const Question = require("../models/question");
const { uploadToCloudinary } = require("../config/cloudinary");
const AppError = require("../utils/AppError");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

exports.autoIngest = async (req, res, next) => {
  try {
    console.log("🚀 [AI Ingest] Protocol Initiated");
    
    if (!req.file) {
      console.log("❌ [AI Ingest] Error: No file uploaded");
      return next(new AppError("Please upload a PDF file", 400));
    }

    const { title, category, seriesId } = req.body;
    if (!title) {
      console.log("❌ [AI Ingest] Error: Missing title");
      return next(new AppError("Title is required", 400));
    }

    console.log(`📂 [AI Ingest] Processing File: ${req.file.originalname}`);

    // 1. Upload PDF to Cloudinary
    console.log("☁️ [AI Ingest] Uploading payload to Cloudinary...");
    let pdfUrl = null;
    try {
      pdfUrl = await uploadToCloudinary(req.file.path, "quizaro_pdfs");
      console.log("✅ [AI Ingest] Cloudinary upload successful");
    } catch (err) {
      console.error("⚠️ [AI Ingest] Cloudinary upload failed, continuing with local data only", err);
    }

    // 2. Extract Text from PDF
    console.log("📄 [AI Ingest] Extracting neural signatures from PDF...");
    let extractedText = "";
    try {
      const dataBuffer = fs.readFileSync(req.file.path);
      const pdf = require("pdf-parse");
      const pdfData = await pdf(dataBuffer);
      extractedText = pdfData.text;
      console.log(`✅ [AI Ingest] Extraction complete. Length: ${extractedText.length} chars`);
    } catch (err) {
      console.error("❌ [AI Ingest] PDF Extraction Failure", err);
      return next(new AppError("Failed to extract text from PDF. The file might be corrupted or image-based (OCR required).", 500));
    }

    if (!extractedText || extractedText.trim().length < 50) {
      console.log("❌ [AI Ingest] Error: Insufficient text content");
      return next(new AppError("PDF contains insufficient text for MCQ generation. Please use a text-based PDF.", 400));
    }

    // 3. Generate MCQs using Gemini
    console.log("🧠 [AI Ingest] Synchronizing with Neural Engine (Gemini 1.5 Flash)...");
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    
    const prompt = `
      Extract multiple choice questions from the following text. 
      For each question, provide exactly 4 options. 
      DO NOT provide the correct answer. 
      Return the result as a JSON array of objects with this structure:
      [{ "questionText": "...", "options": [{ "text": "..." }, { "text": "..." }, { "text": "..." }, { "text": "..." }] }]
      
      IMPORTANT: Return ONLY the JSON array. Do not include any explanation or markdown blocks.
      
      Text: ${extractedText.substring(0, 10000)}
    `;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    let mcqs = [];
    
    try {
      const text = response.text();
      console.log("🤖 [AI Ingest] Neural Engine Response Received");
      
      const jsonMatch = text.match(/\[\s*\{.*\}\s*\]/s);
      const cleanText = jsonMatch ? jsonMatch[0] : text.replace(/```json|```/g, "").trim();
      
      mcqs = JSON.parse(cleanText);
      console.log(`✅ [AI Ingest] Successfully synthesized ${mcqs.length} MCQs`);
    } catch (err) {
      console.error("❌ [AI Ingest] JSON Parse Failure", err);
      return next(new AppError("Neural pattern parsing failed. The AI generated an invalid data structure.", 500));
    }

    if (!mcqs || mcqs.length === 0) {
      return next(new AppError("AI failed to generate any questions from the provided text.", 500));
    }

    // 4. Create Test and Questions
    console.log("💾 [AI Ingest] Persisting intelligence to registry...");
    const test = await TestSeries.create({
      title,
      category: category || "General",
      seriesId: seriesId || null,
      pdfUrl,
      isAutoGenerated: true,
      createdBy: req.user.id,
      isPublished: true,
      totalQuestions: mcqs.length
    });

    const questionsData = mcqs.map((q, index) => ({
      testId: test._id,
      questionText: q.questionText,
      options: q.options,
      correctOption: 0,
      orderIndex: index
    }));

    await Question.insertMany(questionsData);
    console.log("🏁 [AI Ingest] Ingestion Protocol Complete");

    // Clean up local file
    if (fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);

    res.status(201).json({
      status: "success",
      message: "Intelligence successfully ingested and MCQs generated.",
      testId: test._id,
      pdfUrl,
      questionCount: mcqs.length
    });

  } catch (err) {
    console.error("🔥 [AI Ingest] Critical Protocol Failure:", err);
    if (req.file && fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);
    next(err);
  }
};
