const PDFDocument = require("pdfkit");
const Attempt = require("../models/attempt");
const User = require("../models/user");
const TestSeries = require("../models/testSeries");
const Question = require("../models/question");
const AppError = require("../utils/AppError");

exports.exportResultToPDF = async (req, res, next) => {
  try {
    const { attemptId } = req.params;

    const attempt = await Attempt.findById(attemptId);
    if (!attempt) return next(new AppError("Attempt not found", 404));

    const user = await User.findById(attempt.userId);
    const test = await TestSeries.findById(attempt.testId);

    // Initialize PDF Document
    const doc = new PDFDocument({ margin: 50 });

    // Set Response Headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=Scorecard_${user.name.replace(/\s+/g, "_")}_${test?.title.replace(/\s+/g, "_") || "Test"}.pdf`
    );

    doc.pipe(res);

    // --- Header Section ---
    doc
      .fontSize(24)
      .fillColor("#2563eb")
      .text("QUIZARO", { align: "center" })
      .moveDown(0.5);

    doc
      .fontSize(16)
      .fillColor("#111827")
      .text("Official Performance Scorecard", { align: "center" })
      .moveDown(1);

    doc.moveTo(50, 130).lineTo(550, 130).strokeColor("#e5e7eb").stroke();

    // --- User Info Section ---
    doc.moveDown(2);
    doc.fontSize(12).fillColor("#4b5563");
    doc.text(`Candidate Name: ${user.name}`);
    doc.text(`Email Address: ${user.email}`);
    doc.text(`Attempt Date: ${new Date(attempt.createdAt).toLocaleDateString()}`);
    if (test) {
      doc.text(`Examination: ${test.title}`);
    }

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor("#e5e7eb").stroke();
    doc.moveDown(1);

    // --- Score Section ---
    doc.fontSize(20).fillColor("#111827").text("Results Summary", { underline: true });
    doc.moveDown(0.5);
    
    doc.fontSize(14).fillColor(attempt.percentage >= 70 ? "#16a34a" : "#dc2626");
    doc.text(`Final Score: ${attempt.score}`);
    doc.text(`Percentage: ${attempt.percentage}%`);
    doc.fillColor("#4b5563").text(`Time Taken: ${attempt.timeTaken} seconds`);

    doc.moveDown(2);
    doc.fontSize(10).fillColor("#9ca3af");
    doc.text("This document is auto-generated by the Quizaro Platform and serves as an official record of the candidate's performance.");

    doc.end();

  } catch (err) {
    console.error("PDF Export Error:", err);
    if (!res.headersSent) {
      next(new AppError("Failed to generate PDF document", 500));
    }
  }
};
