const mongoose = require("mongoose");

const testSeriesSchema = new mongoose.Schema({
  title: { 
    type: String, 
    required: true 
  },
  description: String,
  duration: Number,
  price: Number,
  totalQuestions: Number,
  category: String,
  seriesId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "QuizSeries",
    required: false
  },
  paperNumber: Number,
  difficulty: {
    type: String,
    enum: ["Easy", "Medium", "Hard"],
    default: "Medium"
  },
  tags: [String],
  createdBy: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: "User" 
  },
  shuffleOptions: {
    type: Boolean,
    default: false
  },
  shuffleQuestions: {
    type: Boolean,
    default: false
  },
  questionTimer: {
    type: Number,
    default: 0
  },
  questionPool: {
    type: Number,
    default: 0
  },
  isPublished: {
    type: Boolean,
    default: false
  },
  pdfUrl: {
    type: String,
    default: null
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  version: {
    type: Number,
    default: 1
  }
}, { timestamps: true });

// Performance Indexes 🔥
testSeriesSchema.index({ seriesId: 1 });
testSeriesSchema.index({ isPublished: 1 });

module.exports = mongoose.model("TestSeries", testSeriesSchema);